### ISSUE TITLE
Still getting internet is required popup

### ISSUE THREAD

**Issue by CheekiBreeki95** [corpnewt/UnPlugged#2]
After following the tutorial and running the script the install prompt pops up and when I press install it gives me the internet is required popup

**Comment by corpnewt** [comment]
What OS are you installing with it?

**Comment by CheekiBreeki95** [comment]
Ventura

**Comment by corpnewt** [comment]
I'll test locally to verify - but I've had others test Ventura with success already.

-CorpNewt

**Comment by corpnewt** [comment]
Yes, I just got confirmation that it works from another user that tested.  I'm betting it's a botched copy.  The installer verifies InstallAssistant.pkg before using it (as far as I know), and if that fails verification, it will attempt to download packages anew.  I would suggest redoing the copy - and ejecting the USB before rebooting to ensure all writes are completed.  But as this does not appear to be an issue with UnPlugged, I'll close this issue.

-CorpNewt
